POST http://localhost:6666/company
Content-Type: application/json

{
  "name": "Fido",
  "created": 2023,
  "product": "Qwernnynynyty"
}

###

GET http://localhost:6666/api/v1/Fido2222226622


###
PUT http://localhost:6666/api/v1/Fido22
Content-Type: application/json

{
  "created": 564656465
}

###

DELETE http://localhost:6666/api/v1/Fido2222226622
